### ISSUE TITLE
moz-extension urls

### ISSUE THREAD

**Issue by Vaelek** [sftblw/Webpage-Sidebar#24]
Any way to coax this into loading moz-extension urls? I was hoping this would allow me to have the uMatrix/uBlock loggers in the sidebar.

**Comment by sftblw** [comment]
- Auto https:// - Adding https automatically is hard-coded when user input URL is not starting with http:// or https://. That can be removed
- I don't know about moz-extension scheme and That looks interesting, but It's not scope of this addin. so, It can be added after investigation far future
- Sorry but I does not maintain this addin actively for now. I think huge refactoring is required before go more far, and I think My programming ability is not yet prepared for it. feel free to fork this addin.

**Comment by Vaelek** [comment]
Oh nice. I simply commented 73-74 and it loaded the URL I wanted without issue.
![image](https://user-images.githubusercontent.com/293765/83186726-9759dc80-a0f2-11ea-837a-b57a6eddc9c9.png)
