### ISSUE TITLE
local files not working since FF latest update 60.0.1 (64-bit)

### ISSUE THREAD

**Issue by wrw1963** [sftblw/Webpage-Sidebar#9]
Up until this latest update a couple of days ago, this local html file displayed fine in the sidebar, using the following path:  D:\firefoxfiles\guides.htm. Now, it does not. Online webpages still work, but not local files.

I also tried this path: file:///D:/firefoxfiles/guides.htm, but it also doesn't work.

I saw that Webpage-Sidebar was updated yesterday, so I removed then reinstalled it. Still no joy. Firefox Add-On Manager says I am using version 0.0.4.

Any help much appreciated!

**Comment by wrw1963** [comment]
That bookmark feature hasn't worked for local files since the big change in FF a few months ago, at least not for me. 

That was the reason I installed your plugin. If it is also not going to work with local files, I don't have a reason to keep using it. :(

**Comment by sftblw** [comment]
Sadly I can't help you 😢
When I tried the bookmark feature on local file on my firefox (62.0a1 nightly) that worked... Trying once again will not hurt anyone. sorry. I suggest you to check your bookmark address starting with `file:///`.
